# Generated by Django 2.1.1 on 2019-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0002_arduino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
