# Generated by Django 2.1.1 on 2019-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0003_auto_20190213_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceControl',
        ),
        migrations.AddField(
            model_name='arduino',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
